<div class="idealdata-config-fieldset idealdata-collapsed" id="idealdata-block">
    <div class="idealdata-config-title" onclick="toggleIdealdataBlock()">
        <p>Introduction</p>
    </div>
    <div class="idealdata-config-content">
        <div class="idealdata-custom-block">
            <p>
                Integrating your Magento platform with a Customer Relationship Management (CRM) system
                can significantly enhance your business operations by automating processes, reducing errors,
                and providing comprehensive customer insights.
            </p>

            <p>
                IdealData.io specializes in seamless Magento-CRM integrations, delivering tangible benefits:
            </p>

            <ul>
                <li><strong>Increased Sales:</strong> Achieve up to a 25% close rate on abandoned cart deals through automated recovery strategies.</li>
                <li><strong>Operational Efficiency:</strong> Eliminate manual errors with automated product synchronization between Magento and your CRM.</li>
                <li><strong>Real-Time Analytics:</strong> Access revenue dashboards for instant sales tracking and informed decision-making.</li>
                <li><strong>Personalized Marketing:</strong> Utilize data-driven insights to craft targeted marketing campaigns that resonate with your audience.</li>
            </ul>

            <p>
                As an Adobe Commerce Bronze Partner, IdealData.io has a proven track record with many multi-million and billion dollar corporations with large volumes of data traveling between platforms on daily basis.
            </p>

            <p>
                Discover how IdealData.io can transform your sales and marketing efforts by seamlessly connecting Magento with your CRM platform.
            </p>

            <p><strong>Just getting started?</strong></p>
            <div class="btn-class">
                <button onclick="window.open('https://idealdata.io/get-a-quote','_blank');" class="action-default scalable save primary ui-button ui-corner-all ui-widget">
                    Request a Quote
                </button>
                <button class="action-default scalable disabled idealdata-secondary-btn">Free Trial</button>
                <p>Coming soon</p>
            </div>
        </div>
    </div>
</div>

<script>
    function toggleIdealdataBlock() {
        const block = document.getElementById('idealdata-block');
        block.classList.toggle('idealdata-collapsed');
    }
</script>
