<div class="idealdata-config-fieldset idealdata-collapsed" id="idealdata-onboarding-block">
    <div class="idealdata-config-title" onclick="toggleIdealdataOnboarding()">Need Assistance with Onboarding?</div>
    <div class="idealdata-config-content">
        <div class="idealdata-onboarding">
            <p>In most cases we can help your get onboarded within 24–48 hours.</p>
            <button onclick="window.open('https://idealdata.io/lp/magento-crm-integration','_blank');"
                    class="action-default scalable idealdata-request">
                Request Onboarding
            </button>
        </div>
    </div>
</div>

<script>
    function toggleIdealdataOnboarding() {
        const el = document.getElementById('idealdata-onboarding-block');
        el.classList.toggle('idealdata-collapsed');
    }
</script>
